//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int CLT_Id { get; set; }
        public string CLT_Nombre { get; set; }
        public int CLT_TCLT_Id { get; set; }
    
        public virtual Tipo_Cliente Tipo_Cliente { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
