//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Empleado_Servicio = new HashSet<Empleado_Servicio>();
        }
    
        public int EMP_Id { get; set; }
        public string EMP_Nombre { get; set; }
        public int EMP_Estado { get; set; }
        public int EMP_TEMP_Id { get; set; }
    
        public virtual ICollection<Empleado_Servicio> Empleado_Servicio { get; set; }
        public virtual Tipo_Empleado Tipo_Empleado { get; set; }
    }
}
