//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Costo_Servicio = new HashSet<Costo_Servicio>();
            this.Empleado_Servicio = new HashSet<Empleado_Servicio>();
        }
    
        public int SRV_Id { get; set; }
        public int SRV_VH_Id { get; set; }
        public int SRV_CLT_Id { get; set; }
        public System.DateTime SRV_FechaInicio { get; set; }
        public System.DateTime SRV_FechaFin { get; set; }
        public string SRV_DireccionInicio { get; set; }
        public string SRV_DireccionFin { get; set; }
        public int SRV_Refencia_Papeleria { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Costo_Servicio> Costo_Servicio { get; set; }
        public virtual ICollection<Empleado_Servicio> Empleado_Servicio { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
