//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cliente
    {
        public Tipo_Cliente()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int TCLT_Id { get; set; }
        public string TCLT_Nombre { get; set; }
        public int TCLT_Porcentaje { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
    }
}
