//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Carga
    {
        public Tipo_Carga()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int TC_Id { get; set; }
        public string TC_Nombre { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
