//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int VH_Id { get; set; }
        public int VH_Capacidad { get; set; }
        public int VH_Consumo { get; set; }
        public int VH_Distancia { get; set; }
        public int VH_Disponibilidad { get; set; }
        public int VH_CostoDepreciacion { get; set; }
        public int VH_TC_Id { get; set; }
    
        public virtual ICollection<Servicio> Servicio { get; set; }
        public virtual Tipo_Carga Tipo_Carga { get; set; }
    }
}
